version: '3.9'

services:
  django:
    build: .
    container_name: LLM-Integrated-Extensible-Management-System
    ports: 
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - "./.env"
    restart: unless-stopped

volumes:
  huggingface_cache:
